import os
from dotenv import load_dotenv

load_dotenv()

class Settings:
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
    BIG_API_KEY = os.getenv("BIG_API_KEY")
    X_API_KEY = os.getenv("X_API_KEY")
    GROQ_API_KEY = os.getenv("GROQ_API_KEY")
    MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")
    COHERE_API_KEY = os.getenv("COHERE_API_KEY")
    BAIDU_ID = os.getenv("BAIDU_ID")
    BAIDU_SEC = os.getenv("BAIDU_SEC")
    TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY")
    OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
    CF_API_KEY = os.getenv("CF_API_KEY")
    OVH_API_KEY = os.getenv("OVH_API_KEY")
    CHUTES_API_KEY = os.getenv("CHUTES_API_KEY")
    TARGON_API_KEY = os.getenv("TARGON_API_KEY")
    FREE_API_KEY = os.getenv("FREE_API_KEY")
    ANYWHERE_API_KEY = os.getenv("ANYWHERE_API_KEY")
    FLOW_API_KEY = os.getenv("FLOW_API_KEY")
    CEREBRAS_API_KEY = os.getenv("CEREBRAS_API_KEY")
    DIFY_API_KEY = os.getenv("DIFY_API_KEY")
    FASTGPT_API_KEY = os.getenv("FASTGPT_API_KEY")
    SILICONFLOW_API_KEY = os.getenv("SILICONFLOW_API_KEY")
    INFINI_API_KEY = os.getenv("INFINI_API_KEY")
    INTERNLM_API_KEY = os.getenv("INTERNLM_API_KEY")
    SCOPE_API_KEY = os.getenv("SCOPE_API_KEY")
    HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")
    FASTAPI_API_KEY = os.getenv("FASTAPI_API_KEY")
    OLLMA_API_KEY = os.getenv("OLLMA_API_KEY")
    ZENMUX_API_KEY = os.getenv("ZENMUX_API_KEY")
    LONGCAT_API_KEY = os.getenv("LONGCAT_API_KEY")
    NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
    LITEROUTER_API_KEY = os.getenv("LITEROUTER_API_KEY")
    ROUTEWAY_API_KEY = os.getenv("ROUTEWAY_API_KEY")
    POIXE_API_KEY = os.getenv("POIXE_API_KEY")
    POIXE_API_KEY = os.getenv("POIXE_API_KEY")
    ZAIWENAI_API_KEY = os.getenv("ZAIWENAI_API_KEY")
    AIHUBMIX_API_KEY = os.getenv("AIHUBMIX_API_KEY")
    ELECTRONHUB_API_KEY = os.getenv("ELECTRONHUB_API_KEY")
    MODELSHUB_API_KEY = os.getenv("MODELSHUB_API_KEY")
    DATAEYES_API_KEY = os.getenv("DATAEYES_API_KEY")
    NAGA_API_KEY = os.getenv("NAGA_API_KEY")
    SPARK_API_KEY = os.getenv("SPARK_API_KEY")
    ASKCODI_API_KEY = os.getenv("ASKCODI_API_KEY")
    GITCODE_API_KEY = os.getenv("GITCODE_API_KEY")
    MAAS_API_KEY = os.getenv("MAAS_API_KEY")
    SCITELY_API_KEY = os.getenv("SCITELY_API_KEY")
    NAVY_API_KEY = os.getenv("NAVY_API_KEY")
    HIDNS_API_KEY = os.getenv("HIDNS_API_KEY")
    OAI_API_KEY = os.getenv("OAI_API_KEY")
    FREETHEAI_API_KEY = os.getenv("FREETHEAI_API_KEY")
    SENSENOVA_API_KEY = os.getenv("SENSENOVA_API_KEY")
    IAMHC_API_KEY = os.getenv("IAMHC_API_KEY")

settings = Settings()
