from config import settings

# A dictionary of all providers, with their API endpoint, model, and message
# The key is the provider name, and the value is a dictionary of its settings
PROVIDERS = {
    "baidu": {
        "url": "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-speed-128k",
        "auth_method": "baidu",
        "model": "modelBaidu",
        "message": "messageBaidu",
    },
    "big": {
        "url": "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        "key": settings.BIG_API_KEY,
        "model": "modelBig",
        "message": "messageBig",
    },
    "groq": {
        "url": "https://api.groq.com/openai/v1/chat/completions",
        "key": settings.GROQ_API_KEY,
        "model": "modelGroq",
        "message": "messageGroq",
    },
    "mistral": {
        "url": "https://api.mistral.ai/v1/chat/completions",
        "key": settings.MISTRAL_API_KEY,
        "model": "modelMistral",
        "message": "messageMistral",
    },
    # "together": {
    #     "url": "https://api.together.xyz/v1/chat/completions",
    #     "key": settings.TOGETHER_API_KEY,
    #     "model": "modelTogether",
    #     "message": "messageTogether",
    # },
    "gemini_openai": {
        "url": "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
        "key": settings.GEMINI_API_KEY,
        "model": "modelGemini",
        "message": "messageGemini",
    },
    "openai_azure": {
        "url": "https://models.github.ai/inference/chat/completions",
        "key": settings.OPENAI_API_KEY,
        "model": "modelOpenAi",
        "message": "messageOpenAi",
    },
    "grok_azure": {
        "url": "https://models.github.ai/inference/chat/completions",
        "key": settings.OPENAI_API_KEY,
        "model": "modelGrok",
        "message": "messageGrok",
    },
    "openrouter": {
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "key": settings.OPENROUTER_API_KEY,
        "model": "modelOpenRouter",
        "message": "messageOpenRouter",
    },
    # "chutes": {
    #     "url": "https://chutes-{model}.chutes.ai/v1/chat/completions",
    #     "key": settings.CHUTES_API_KEY,
    #     "model": "modelChutes",
    #     "message": "messageChutes",
    # },
    "cohere": {
        "url": "https://api.cohere.com/v2/chat",
        "key": settings.COHERE_API_KEY,
        "model": "modelCohere",
        "message": "messageCohere",
    },
    "cloudflare": {
        "url": "https://api.cloudflare.com/client/v4/accounts/53a4ab7d625890920e433def35a30c59/ai/v1/responses",
        "key": settings.CF_API_KEY,
        "model": "modelCF",
        "message": "messageCF",
    },
    # "ovh": {
    #     "url": "https://{model}.endpoints.kepler.ai.cloud.ovh.net/api/openai_compat/v1/chat/completions",
    #     "key": settings.OVH_API_KEY,
    #     "model": "modelOVH",
    #     "message": "messageOVH",
    # },
    # "targon": {
    #     "url": "https://api.targon.com/v1/chat/completions",
    #     "key": settings.TARGON_API_KEY,
    #     "model": "modelTargon",
    #     "message": "messageTargon",
    # },
    "pollination": {
        "url": "https://text.pollinations.ai/",
        "model": "modelPollination",
        "message": "messagePollination",
    },
    "dify": {
        "url": "https://api.dify.ai/v1/workflows/run",
        "key": settings.DIFY_API_KEY,
    },
    "vectorshift": {
        "url": "https://api.vectorshift.ai/v1/pipeline/67bf6cfa207790ac67e917d0/run",
        "key": settings.FLOW_API_KEY,
    },
        "free": {
        "url": "https://free.v36.cm/v1/chat/completions",
        "key": settings.FREE_API_KEY,
        "model": "modelFree",
        "message": "messageFree",
    },
    "chatanywhere": {
        "url": "https://api.chatanywhere.org/v1/chat/completions",
        "key": settings.ANYWHERE_API_KEY,
        "model": "modelAnywhere",
        "message": "messageAnywhere",
    },
    "cerebras": {
        "url": "https://api.cerebras.ai/v1/chat/completions",
        "key": settings.CEREBRAS_API_KEY,
        "model": "modelCerebras",
        "message": "messageCerebras",
    },
    "fastgpt": {
        "url": "https://cloud.fastgpt.cn/api/v1/chat/completions",
        "key": settings.FASTGPT_API_KEY,
        "model": "modelFastGPT",
        "message": "messageFastGPT",
    },    
    "siliconflow": {
        "url": "https://api.siliconflow.cn/v1/chat/completions",
        "key": settings.SILICONFLOW_API_KEY,
        "model": "modelSiliconFlow",
        "message": "messageSiliconFlow",
    },        
    "infini": {
        "url": "https://cloud.infini-ai.com/maas/v1/chat/completions",
        "key": settings.INFINI_API_KEY,
        "model": "modelInfini",
        "message": "messageInfini",
    },   
    # "internlm": {
    #     "url": "https://internlm-chat.intern-ai.org.cn/puyu/api/v1/chat/completions",
    #     "key": settings.INTERNLM_API_KEY,
    #     "model": "modelInternlm",
    #     "message": "messageInternlm",
    # },
    "scope": {
        "url": "https://api-inference.modelscope.cn/v1/chat/completions",
        "key": settings.SCOPE_API_KEY,
        "model": "modelScope",
        "message": "messageScope",
    },               
    "huggingface": {
        "url": "https://router.huggingface.co/featherless-ai/v1/chat/completions",
        "key": settings.HUGGINGFACE_API_KEY,
        "model": "modelHuggingface",
        "message": "messageHuggingface",
    }, 
    "ollma": {
        "url": "https://ollama.com/v1/chat/completions",
        "key": settings.OLLMA_API_KEY,
        "model": "modelOllma",
        "message": "messageOllma",
    }, 
    "zenmux": {
        "url": "https://zenmux.ai/api/v1/chat/completions",
        "key": settings.ZENMUX_API_KEY,
        "model": "modelZenmux",
        "message": "messageZenmux",
    }, 
    "longcat": {
        "url": "https://api.longcat.chat/openai/v1/chat/completions",
        "key": settings.LONGCAT_API_KEY,
        "model": "modelLongcat",
        "message": "messageLongcat",
    }, 
    "nvidia": {
        "url": "https://integrate.api.nvidia.com/v1/chat/completions",
        "key": settings.NVIDIA_API_KEY,
        "model": "modelNvidia",
        "message": "messageNvidia",
    }, 
    "literouter": {
        "url": "https://api.literouter.com/v1/chat/completions",
        "key": settings.LITEROUTER_API_KEY,
        "model": "modelLiterouter",
        "message": "messageLiterouter",
    }, 
    "routeway": {
        "url": "https://api.routeway.ai/v1/chat/completions",
        "key": settings.ROUTEWAY_API_KEY,
        "model": "modelRouteway",
        "message": "messageRouteway",
    }, 
    "poixe": {
        "url": "https://api.poixe.com/v1/chat/completions",
        "key": settings.POIXE_API_KEY,
        "model": "modelPoixe",
        "message": "messagePoixe",
    }, 
    "zaiwenai": {
        "url": "https://back.zaiwenai.com/api/v1/ai/chat/completions",
        "key": settings.ZAIWENAI_API_KEY,
        "model": "modelZaiwenai",
        "message": "messageZaiwenai",
    }, 
    # "aihubmix": {
    #     "url": "https://aihubmix.com/v1/chat/completions",
    #     "key": settings.AIHUBMIX_API_KEY ,
    #     "model": "modelAihubmix",
    #     "message": "messageAihubmix",
    # }, 
    "electronhub": {
        "url": "https://api.electronhub.ai/v1/chat/completions",
        "key": settings.ELECTRONHUB_API_KEY ,
        "model": "modelElectronhub",
        "message": "messageElectronhub",
    }, 
    "modelshub": {
        "url": "https://www.models-hub.net/v1/chat/completions",
        "key": settings.MODELSHUB_API_KEY ,
        "model": "modelModelshub",
        "message": "messageModelshub",
    },    
    "dataeyes": {
        "url": "https://platform.dataeyes.ai/v1/chat/completions",
        "key": settings.DATAEYES_API_KEY ,
        "model": "modelDataeyes",
        "message": "messageDataeyes",
    }, 
    "naga": {
        "url": "https://api.naga.ac/v1/chat/completions",
        "key": settings.NAGA_API_KEY ,
        "model": "modelNage",
        "message": "messageNage",
    }, 
    "spark": {
        "url": "https://spark-api-open.xf-yun.com/v1/chat/completions",
        "key": settings.SPARK_API_KEY ,
        "model": "modelSpark",
        "message": "messageSpark",
    }, 
    "askcodi": {
        "url": "https://api.askcodi.com/v1/chat/completions",
        "key": settings.ASKCODI_API_KEY ,
        "model": "modelAskcodi",
        "message": "messageAskcodi",
    },   
    "gitcode": {
        "url": "https://api-ai.gitcode.com/v1/chat/completions",
        "key": settings.GITCODE_API_KEY ,
        "model": "modelGitcode",
        "message": "messageGitcode",
    },
    "maas": {
        "url": "https://maas-api.cn-huabei-1.xf-yun.com/v2/chat/completions",
        "key": settings.MAAS_API_KEY ,
        "model": "modelMaas",
        "message": "messageMaas",
    },
    
    "scitely": {
        "url": "https://api.scitely.com/v1/chat/completions",
        "key": settings.SCITELY_API_KEY ,
        "model": "modelScitely",
        "message": "messageScitely",
    },
    "navy": {
        "url": "https://api.navy/v1/chat/completions",
        "key": settings.NAVY_API_KEY ,
        "model": "modelNavy",
        "message": "messageNavy",
    },
    "hidns": {
        "url": "https://openai.good.hidns.vip/v1/chat/completions",
        "key": settings.HIDNS_API_KEY ,
        "model": "modelHidns",
        "message": "messageHidns",
    },
    "oai": {
        "url": "https://oai2api.com/v1/chat/completions",
        "key": settings.OAI_API_KEY ,
        "model": "modelOai",
        "message": "messageOai",
    },
   "freetheai": {
        "url": "https://api.freetheai.xyz/v1/chat/completions",
        "key": settings.FREETHEAI_API_KEY ,
        "model": "modelFreetheai",
        "message": "messageFreetheai",
    },
   "sensenova": {
        "url": "https://token.sensenova.cn/v1/chat/completions",
        "key": settings.SENSENOVA_API_KEY ,
        "model": "modelSensenova",
        "message": "messageSensenova",
    },
   "iamhc": {
        "url": "https://api.iamhc.cn/v1/chat/completions",
        "key": settings.IAMHC_API_KEY ,
        "model": "modelIamhc",
        "message": "messageIamhc",
    },
   "agnes": {
        "url": "https://apihub.agnes-ai.com/v1/chat/completions",
        "key": settings.AGNES_API_KEY ,
        "model": "modelAgnes",
        "message": "messageAgnes",
    },
   "gitlawb": {
        "url": "https://opengateway.gitlawb.com/v1/chat/completions",
        "key": settings.GITLAWB_API_KEY ,
        "model": "modelGitlawb",
        "message": "messageGitlawb",
    },
   "pooled": {
        "url": "https://ai.pooled.dev/v1/chat/completions",
        "key": settings.POOLED_API_KEY ,
        "model": "modelPooled",
        "message": "messagePooled",
    },
   "streamlakeapi": {
        "url": "https://wanqing.streamlakeapi.com/api/gateway/v1/endpoints/chat/completions587c66ea06e24b86a48a566fc7d8cea6",
        "key": settings.STREAMLAKEAPI_API_KEY ,
        "model": "modelStreamlakeapi",
        "message": "messageStreamlakeapi",
    },
   "openmodel": {
        "url": "https://api.openmodel.ai/v1/responses",
        "key": settings.OPENMODEL_API_KEY ,
        "model": "modelOpenmodel",
        "message": "messageOpenmodel",
    },
   "dxnt": {
        "url": "https://www.dxnt.com/v1/chat/completions",
        "key": settings.DXNT_API_KEY ,
        "model": "modelDxnt",
        "message": "messageDxnt",
    },
   "cline": {
        "url": "https://api.cline.bot/api/v1/chat/completions",
        "key": settings.CLINE_API_KEY ,
        "model": "modelCline",
        "message": "messageCline",
    },
   "bynara": {
        "url": "https://router.bynara.id/v1/chat/completions",
        "key": settings.BYNARAE_API_KEY ,
        "model": "modelBynara",
        "message": "messageBynara",
    },
}
